import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const farroBold = localFont({
  src: "/fonts/Farro-Bold.woff",
  variable: "--font-farro-bold",
  weight: "700",
  display: "swap",
});

const interBold = localFont({
  src: "/fonts/Inter-Bold.woff",
  variable: "--font-inter-bold",
  weight: "700",
  display: "swap",
});

export const metadata: Metadata = {
  title: "learing test",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-lime text-white text-2xl p-10 bg-red-100 text-xl antialiased">
        {children}
      </body>
    </html>
  );
}
