import type { Metadata } from "next";
import "./globals.css";
import ClientLayout from "./clientlayout/ClientLayout";

export const metadata: Metadata = {
  title: "learing test",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
